config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticated :user do
    root to: "doctrines#index", as: :authenticated_root
  end

  root to: redirect('/sign_in')

  resources :videos
  get 'latest/videos' => 'videos#latest'

  resources :operations

  resources :years do
    resources :months
  end

  resources :recruit_contacts
  get 'search/recruit_contacts' => 'recruit_contacts#search_name'

  resources :recruit_requirements
  resources :roles

  resources :members, only: [:index, :show]
  get 'members/add_new_api'
  get 'members/add_temporary_member'
  get 'refresh_member_list' => 'members#refresh_member_list'

  resources :fac_war_systems, only: [:index]
  get 'refresh_fac_war_systems' => 'fac_war_systems#refresh_fac_war_systems'

  resources :mission_groups do
    resources :missions do
      put 'obstructed' => 'missions#mark_obstructed'
      put 'complete' => 'missions#mark_complete'
      put 'incomplete' => 'missions#mark_incomplete'
    end

  end
  get 'accessible_agents' => 'missions#accessible_agents'

  resources :doctrines do
    resources :fittings
  end

  resources :fleet_commanders do
    resources :ratings
  end
end

app/models/fitting.rb
# == Schema Information
#
# Table name: fittings
#
#  id                   :integer          not null, primary key
#  name                 :string
#  hull                 :string
#  race                 :string
#  fleet_role           :string
#  description          :text
#  progression          :string
#  progression_position :integer
#  eft_string           :string
#  ship_dna             :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  doctrine_id          :integer
#

class Fitting < ActiveRecord::Base
  belongs_to :doctrine

  validates :name, presence: true
  validates :hull, presence: true
  validates :race, presence: true
  validates :fleet_role, presence: true
  #validates :description, presence: true
  validates :progression, presence: true
  validates :progression_position, presence: true
  validates :eft_string, presence: true
end

app/controllers/fittings_controller.rb
class FittingsController < ApplicationController
  def index
    @doctrine = Doctrine.find(params[:doctrine_id])
    @fittings = Fitting.where(doctrine_id: params[:doctrine_id])
    authorize @fittings[0]
  end

  def create
    @fitting = Fitting.new(create_fitting_params)
    authorize @fitting
    # Split the EFT String apart line by line
    eft_string = params[:eft_string]
    eft_string_components = eft_string.split("\n")

    # Extract the hull and name data from the first line
    clean_info_bracket = eft_string_components[0].chomp
    info_bracket = clean_info_bracket.slice(1..clean_info_bracket.length-2).split(", ")
    @fitting.hull = info_bracket[0]
    @fitting.name = info_bracket[1]
    @fitting.race = ChrRace.where(raceID: InvType.where("\"typeName\" = ?", @fitting.hull).pluck("\"raceID\""))[0].raceName
    @fitting.ship_dna = create_ship_dna(@fitting)
    if @fitting.save
      doctrine = @fitting.doctrine
      redirect_to doctrine_path(@fitting.doctrine)
    else
      @doctrine = Doctrine.find(params[:doctrine_id])
      render 'new'
    end
  end

  def new
    @doctrine = Doctrine.find(params[:doctrine_id])
    @fitting = Fitting.new(doctrine_id: @doctrine.id)
    authorize @fitting
  end

  def edit
    @fitting = Fitting.find(params[:id])
    authorize @fitting
  end

  def show
    @fitting = Fitting.find(params[:id])
    authorize @fitting
  end

  def update
    @fitting = Fitting.find(params[:id])
    authorize @fitting

    if @fitting.update_attributes(create_fitting_params)
      if @fitting.save
        redirect_to doctrine_fittings_path(@fitting)
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def destroy
    @fitting = Fitting.find(params[:id])
    authorize @fitting

    @fitting.destroy
    redirect_to doctrine_fittings_path(params[:doctrine_id])
  end

  private
    def create_fitting_params
      params.permit(:name, :hull, :race, :fleet_role, :description, :progression, :progression_position, :eft_string, :doctrine_id)
    end

    def create_ship_dna(fitting)
      # Split the EFT String on each new line character
      eft_string_split = fitting.eft_string.split("\n")
      # Remove the info bracket as it isn't needed.
      eft_string_split.delete_at(0)
      # Iterate over each line
      # dna lows, meds, highs, subs, rigs, drones/charges?
      dna = [{},{},{},{},{},{}]
      dna_counter = 0
      eft_string_split.each do |line|
        # Strip the trailing newline character
        line = line.chomp
        puts line
        # If the line is blank
        if line.blank?
          # Increment the dna counter
          dna_counter+=1
          if dna_counter == 3
            unless ["Proteus","Loki","Legion","Tengu"].include?(fitting.hull)
              dna_counter += 1
            end
          end

          if dna_counter == 6
            break
          end
        else
          # Check the item for charges
          ammo_check_split = line.split(", ")
          if ammo_check_split.length > 1
            # Add the charge to the charges hash
            if dna[5]["#{ammo_check_split[1]}"]
              dna[5]["#{ammo_check_split[1]}"] +=1
            else
              dna[5].store("#{ammo_check_split[1]}", 1)
            end
            # Remove the charge from the line
            line = ammo_check_split[0].chomp(",")
          end
          # Check if the item already exists in the dna_hash
          if dna[dna_counter]["#{line}"]
            # Increment the count of that item
            dna[dna_counter]["#{line}"]+=1
          else
            line_value = 1
            # If the line ends in 'x5', etc, ensure that value is captured and passed into the hash
            match_data = /x[0-9]+$/.match(line)
            if match_data
              matched_string = match_data.to_s
              # Trim the value off the string
              line = line.slice(0,(line.length - matched_string.length)-1)
              # Update the line_value value
              line_value = /[0-9]+/.match(matched_string).to_s.to_i
            end
            # Add the item to the list.
            dna[dna_counter].store("#{line}", line_value)
          end
        end
      end
      puts dna
      # Convert the DNA hash to a DNA string with type IDs
      dna_string = ""
      # Retrieve ship typeID
      ship_typeID = InvType.where("\"typeName\" = ?", fitting.hull).pluck(:typeID)[0]
      dna_string = dna_string + "#{ship_typeID}:"
      # Check for subsystems
      unless dna[3].empty?
        # Iterate over the hash
        dna[3].each do |key, value|
          # Retrieve the typeID for each key
          typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
          # Append the typeID & quantity to the dna string
          dna_string = dna_string + "#{typeID};#{value}:"
        end
      end
      # Iterate over the high slots hash
      dna[2].each do |key, value|
        # Retrieve the typeID for each key
        typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
        # Append the typeID & quantity to the dna string
        dna_string = dna_string + "#{typeID};#{value}:"
      end

      # Iterate over the med slots hash
      dna[1].each do |key, value|
        # Retrieve the typeID for each key
        typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
        # Append the typeID & quantity to the dna string
        dna_string = dna_string + "#{typeID};#{value}:"
      end

      # Iterate over the low slots hash
      dna[0].each do |key, value|
        # Retrieve the typeID for each key
        typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
        # Append the typeID & quantity to the dna string
        dna_string = dna_string + "#{typeID};#{value}:"
      end

      # Iterate over the rigs hash
      dna[4].each do |key, value|
        # Retrieve the typeID for each key
        typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
        # Append the typeID & quantity to the dna string
        dna_string = dna_string + "#{typeID};#{value}:"
      end

      # Iterate over the charges hash
      dna[5].each do |key, value|
        # Retrieve the typeID for each key
        typeID = InvType.where("\"typeName\" = ?", key).pluck(:typeID)[0]
        # Append the typeID & quantity to the dna string
        dna_string = dna_string + "#{typeID};#{value}:"
      end
      dna_string = dna_string + ":"

      return dna_string
    end
end

app/helpers/fittings_helper.rb
module FittingsHelper
end

app/views/fittings/create.html.erb
<h1>Fittings#create</h1>
<p>Find me in app/views/fittings/create.html.erb</p>

app/views/fittings/edit.html.erb
<h1>Fittings#edit</h1>
<p>Find me in app/views/fittings/edit.html.erb</p>

app/views/fittings/index.html.erb
<div class="doctrine__fitting-index">
  <h1> <%= @doctrine.name %> Fittings List </h1>
  <div class="doctrine__nav-links">
    <%= link_to "Doctrine Progressions", doctrine_path(@doctrine) %>
    <% if current_user.director %>
      <%= link_to "Add New Fitting", new_doctrine_fitting_path(@doctrine) %>
    <% end %>
  </div>
  <table>
    <thead>
      <th> Name </th>
      <th> Ship </th>
      <th> Race </th>
      <th> Fleet Role </th>
      <th> Progression </th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @fittings.each do |fitting| %>
      <tr>
       <th> <%= fitting.name %> </th>
       <th> <%= fitting.hull %> </th>
       <th> <%= fitting.race %> </th>
       <th> <%= fitting.fleet_role %> </th>
       <th> <%= fitting.progression %> </th>
       <th> <%= link_to "Fit", doctrine_fitting_path(@doctrine, fitting) %> </td>
       <% if @doctrine.editable_by_user?(current_user) %>
        <td> <%= link_to "Edit", edit_doctrine_fitting_path(@doctrine, fitting) %> </td>
        <td> <%= link_to "Delete", doctrine_fitting_path(@doctrine, fitting), confirm: "Are you sure?", method: :delete %> </td>
      <% else %>
        <td> </td>
        <td> </td>
      <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fittings/new.html.erb
<h1> Add new Fit to <%= @doctrine.name %> </h1>

<%= form_tag(doctrine_fittings_path(@doctrine, @fitting)) do %>
  <%= render "shared/error_messages", :target => @fitting %>
  <div class="form-group">
    <%= label_tag 'fleet_role', "Fleet Role" %>
    <%= text_field_tag :fleet_role, nil, :placeholder => "Scram Ceptor" %>
  </div>
  <div class="form-group">
    <div class="form-group__label">
      <%= label_tag 'description', "Fit Description" %>
    </div>
    <%= text_area_tag :description, nil, size: "50x5", :placeholder => "This description will display on the fit's page. The description should describe in detail the manner in which the ship is to be flown." %>
  </div>
  <div class="form-group">
    <%= label_tag 'progression', "Skill Progression" %>
    <%= text_field_tag :progression, nil, :placeholder => "Hybrids" %>
  </div>
  <div class="form-group">
    <%= label_tag 'progression_position', "Skill Progression Position" %>
    <%= text_field_tag :progression_position, nil, :placeholder => "1" %>
  </div>
  <div class="form-group">
    <div class="form-group__label">
      <%= label_tag 'eft_string', "Paste EFT Fit" %>
    </div>
    <%= text_area_tag :eft_string, nil, size: "75x50", :placeholder => "Seriously? Just fucking paste it noob." %>
  </div>
  <div class="form-group">
    <%= submit_tag "Add new Fit to #{@doctrine.name}" %>
  </div>
<% end %>

app/views/fittings/show.html.erb
<div class="fitting">
  <div class="fitting__traits">
    <div class="fitting__race">
      <%= @fitting.race %>
    </div>
    <div class="fitting__progression">
      <%= @fitting.progression %>
    </div>
    <div class="fitting__hull">
      <%= @fitting.hull %>
    </div>
  </div>
  <div class="doctrine__nav-links">
    <%= link_to "#{@fitting.doctrine.name} Progressions", doctrine_path(@fitting.doctrine) %>
  </div>
  <div class="clear"/>
  <div class="fitting__details">
    <div class="fitting__render">
      <% ship_type_id = @fitting.ship_dna.split(":")[0] %>
      <img src="http://image.eveonline.com/render/<%= ship_type_id %>_256.png">
    </div>
    <div class="fitting__name">
      Name: <%= @fitting.name %>
    </div>
    <div class="fitting__fleet-role">
      Role: <%= @fitting.fleet_role %>
    </div>
  </div>
  <div class="clear"/>
  <div class="fitting__description">
    <div class="fitting__description-title">
      Description
    </div>
    <%= @fitting.description %>
  </div>
  <div class="fitting__types">
    <div class="fitting__ship-dna">
      <a class="fitting__ship-dna__ig-link" href="\javascript:CCPEVE.showFitting('<%= @fitting.ship_dna %>');\">Show In Game Fitting</a>
    </div>
    <div class="fitting__eft-string">
      <pre><%= @fitting.eft_string %>
      </pre>
    </div>
  </div>
</div>

app/views/fittings/update.html.erb
<h1>Fittings#update</h1>
<p>Find me in app/views/fittings/update.html.erb</p>