config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticated :user do
    root to: "doctrines#index", as: :authenticated_root
  end

  root to: redirect('/sign_in')

  resources :videos
  get 'latest/videos' => 'videos#latest'

  resources :operations

  resources :years do
    resources :months
  end

  resources :recruit_contacts
  get 'search/recruit_contacts' => 'recruit_contacts#search_name'

  resources :recruit_requirements
  resources :roles

  resources :members, only: [:index, :show]
  get 'members/add_new_api'
  get 'members/add_temporary_member'
  get 'refresh_member_list' => 'members#refresh_member_list'

  resources :fac_war_systems, only: [:index]
  get 'refresh_fac_war_systems' => 'fac_war_systems#refresh_fac_war_systems'

  resources :mission_groups do
    resources :missions do
      put 'obstructed' => 'missions#mark_obstructed'
      put 'complete' => 'missions#mark_complete'
      put 'incomplete' => 'missions#mark_incomplete'
    end

  end
  get 'accessible_agents' => 'missions#accessible_agents'

  resources :doctrines do
    resources :fittings
  end

  resources :fleet_commanders do
    resources :ratings
  end
end

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_nav_links.html.erb
<div class="header">
  <%= link_to(root_path) do %>
  <div class="header__logo">
    <%= image_tag("http://image.eveonline.com/Corporation/98383644_128.png") %>
    <div class="header__logo-text">
      ANTIGEN
    </div>
  </div>
  <% end %>
  <div class="header__nav-links">
    <% if current_user %>
      <div class="header__nav-link">
        <%= link_to('Doctrines', doctrines_path) %>
      </div>
      <% if current_user.member %>
        <div class="header__nav-link">
          <%= link_to('Missions', mission_groups_path) %>
        </div>
      <% end %>
      <% if current_user.director %>
        <div class="header__nav-link">
          <%= link_to "Latest Uploads", latest_videos_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Upload Video", new_video_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Operation List", operations_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Create Op", new_operation_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Year List", years_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Latest Contacts", recruit_contacts_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Add new Contact", new_recruit_contact_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Recruitment Requirements", recruit_requirements_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Roles", roles_path %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Members", members_path  %>
        </div>
        <div class="header__nav-link">
          <%= link_to "Systems", fac_war_systems_path %>
        </div>
      <% end %>
      <div class="header__nav-link">
        <%= link_to('Logout', destroy_user_session_path) %>
      </div>
    <% end %>
  </div>
</div>