config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticated :user do
    root to: "doctrines#index", as: :authenticated_root
  end

  root to: redirect('/sign_in')

  resources :videos
  get 'latest/videos' => 'videos#latest'

  resources :operations

  resources :years do
    resources :months
  end

  resources :recruit_contacts
  get 'search/recruit_contacts' => 'recruit_contacts#search_name'

  resources :recruit_requirements
  resources :roles

  resources :members, only: [:index, :show]
  get 'members/add_new_api'
  get 'members/add_temporary_member'
  get 'refresh_member_list' => 'members#refresh_member_list'

  resources :fac_war_systems, only: [:index]
  get 'refresh_fac_war_systems' => 'fac_war_systems#refresh_fac_war_systems'

  resources :mission_groups do
    resources :missions do
      put 'obstructed' => 'missions#mark_obstructed'
      put 'complete' => 'missions#mark_complete'
      put 'incomplete' => 'missions#mark_incomplete'
    end

  end
  get 'accessible_agents' => 'missions#accessible_agents'

  resources :doctrines do
    resources :fittings
  end

  resources :fleet_commanders do
    resources :ratings
  end
end

app/models/doctrine.rb
# == Schema Information
#
# Table name: doctrines
#
#  id                  :integer          not null, primary key
#  name                :string
#  short_description   :string
#  long_description    :text
#  access_by_hierarchy :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  abbreviation        :string
#

class Doctrine < ActiveRecord::Base

  has_many :fittings
  has_many :roles
  has_and_belongs_to_many :roles

  validates :name, presence: true
  validates :short_description, presence: true
  validates :abbreviation, presence: true

  # Determine if the user should have access to this doctrine or not
  def accessible_to_user?(user)
    # Retrieve the doctrine's roles
    doctrine_roles = self.roles
    user_roles = user.roles
    # if access_by_hierarchy, then the doctrine should be accessible to all roles
    # listed and all roles >= the highest hierarchy among the listed roles
    if self.access_by_hierarchy
      # Determine highest of the doctrine's roles
      doctrine_hierarchy = doctrine_roles.pluck(:hierarchy_ranking).sort
      # Determine highest of the user's roles
      user_hierarchy = user_roles.pluck(:hierarchy_ranking).sort

      # Compare the two highest roles
      if user_hierarchy.last >= doctrine_hierarchy.last
        # if user is equal to or greater
        return true
      else
        # otherwise check for role match
        roles_match?(user_roles, doctrine_roles)
      end
    # if access_by_hierarchy is false, then
    else
      # Check if the roles match
      roles_match?(user_roles, doctrine_roles)
    end
  end

  def editable_by_user?(user)
    user.director
  end

  def creatable_by_user?(user)
    user.director
  end

  private
    def roles_match?(role_array_one, role_array_two)
      intersection = role_array_one & role_array_two
      if intersection.empty?
        return false
      else
        return true
      end
    end
end

app/controllers/doctrine_controller.rb
class DoctrineController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/doctrines_controller.rb
class DoctrinesController < ApplicationController
  def index
    # This is messy, and can probably be done easier.
    @doctrines = Doctrine.where(id: DoctrinesRole.where(role_id: current_user.roles.pluck(:id)).pluck(:doctrine_id))
  end

  def new
    @doctrine = Doctrine.new
    authorize @doctrine

    @roles = current_user.less_or_equal_roles
  end

  def create
    @doctrine = Doctrine.new(create_doctrine_params)
    authorize @doctrine
    if @doctrine.save
      # Batch insert all the roles the doctrine should have into the database
      doctrines_roles = []
      params[:roles].each do |role_id|
        doctrines_roles << {doctrine_id: @doctrine.id, role_id: role_id}
      end
      DoctrinesRole.create(doctrines_roles)

      redirect_to doctrines_path
    else
      @roles = current_user.less_or_equal_roles
      render 'new'
    end
  end

  def show
    @doctrine = Doctrine.find(params[:id])
    authorize @doctrine

    fittings = @doctrine.fittings
    # @fittings_hash contains the organized doctrine for display to the user.
    @fittings_hash = {}
    # Iterater over each fit
    fittings.each do |fit|
      # if there is already a key in the hash for the race
      if @fittings_hash["#{fit.race}"].present?
        # Check if the fit's progression exists as well
        if @fittings_hash["#{fit.race}"]["#{fit.progression}"].present?
          # If it it does, add the fit to the progression
          @fittings_hash["#{fit.race}"]["#{fit.progression}"] << fit
          # and sort the fit array by progression_position
          @fittings_hash["#{fit.race}"]["#{fit.progression}"].sort_by! {|a| a.progression_position}
        # Otherwise,
        else
          # store a new key value pair containing the progression & the fit into the race hash
          @fittings_hash["#{fit.race}"].store("#{fit.progression}", [fit])
        end
      # Otherwise,
      else
        # Store the race in the hash, with a hash as it's value.
        # The child hash should have the fit's progression as its key and the fit should
        # be in an array as that key's value
        @fittings_hash.store("#{fit.race}", {"#{fit.progression}" => [fit]})
      end
    end
  end

  def edit
    @doctrine = Doctrine.find(params[:id])
    authorize @doctrine
    # Edit should only be available to the doctrine owner? Think on this
  end

  def update
    @doctrine = Doctrine.find(params[:id])
    authorize @doctrine

    if @doctrine.update_attributes(create_doctrine_params)
      if @doctrine.save
        # Update roles if necessary, to determine this:
        # Retrieve the new role and old role ids
        new_role_ids = params[:roles]
        old_role_ids = @doctrine.roles.pluck(:id)
        # Determine the overlap between new and old
        intersection = new_role_ids & old_role_ids
        # Check if any of the roles have changed
        unless intersection.length == new_role_ids.length && intersection.length == old_role_ids.length
          # If they have;
          # Remove any overlap from both arrays
          new_role_ids.delete(intersection)
          old_role_ids.delete(intersection)
          # Delete remaining old roles
          DoctrinesRole.where(doctrine_id: @doctrine.id, role_id: [old_role_ids])
          # Create remaining new roles
          create_new_roles = []
          new_role_ids.each do |role_id|
            create_new_roles << {doctrine_id: @doctrine.id, role_id: role_id}
          end
          DoctrinesRole.create(create_new_roles)
        end
        redirect_to doctrines_path
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def destroy
    @doctrine = Doctrine.find(params[:id])
    authorize @doctrine
  end

  private
    def create_doctrine_params
      params.permit(:name, :abbreviation, :short_description, :long_description, :access_by_hierarchy)
    end
end

app/helpers/doctrine_helper.rb
module DoctrineHelper
end

app/views/doctrines/create.html.erb
<h1>Doctrine#create</h1>
<p>Find me in app/views/doctrine/create.html.erb</p>

app/views/doctrines/edit.html.erb
<h1>Doctrine#edit</h1>
<p>Find me in app/views/doctrine/edit.html.erb</p>

app/views/doctrines/index.html.erb
<div class="doctrine-list">
  <h1>Doctrines</h1>
  <div class="doctrine-list__nav-links">
    <% if current_user.director %>
      <%= link_to "Add New Doctrine", new_doctrine_path %>
    <% end %>
  </div>
  <table>
    <thead>
      <th> Name </th>
      <th> Abbreviation </th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @doctrines.each do |doctrine| %>
      <tr>
        <td> <%= link_to "#{doctrine.name}", doctrine_path(doctrine) %> </td>
        <td> <%= doctrine.abbreviation %> </td>
        <% if doctrine.editable_by_user?(current_user) %>
          <td> <%= link_to "Edit", edit_doctrine_path(doctrine) %> </td>
          <td> <%= link_to "Delete", doctrine_path(doctrine), confirm: "Are you sure?", method: :delete %> </td>
        <% else %>
          <td> </td>
          <td> </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/doctrines/new.html.erb
<h1>Add new Doctrine</h1>
<%= form_tag(@doctrine) do  %>
  <%= render "shared/error_messages", :target => @doctrine %>
  <div class="form-group">
    <%= label_tag 'name', "Doctrine Name" %>
    <%= text_field_tag 'name', nil, :placeholder => "Shield Nano Brawler" %>
  </div>
  <div class="form-group">
    <%= label_tag :abbreviation, "Doctrine Abbreviation" %>
    <%= text_field_tag :abbreviation, nil, :placeholder => "SNB" %>
  </div>
  <div class="form-group">
    <%= label_tag :short_description, "Short Description" %>
    <%= text_area_tag :short_description, nil, size: "50x5", :placeholder => "This description will display on the doctrine list page." %>
  </div>
  <div class ="form-group">
    <%= label_tag :long_description, "Long Description" %>
    <%= text_area_tag :long_description, nil, size: "50x10", :placeholder => "This description will display on this doctrine's page." %>
  </div>
  <div class="form-group">
    <%= label_tag :roles, "Accessible To" %>
    <%= select_tag "roles", options_from_collection_for_select(@roles, "id", "name"), multiple: true %>
  </div>
  <div class="form-group">
    <%= label_tag :access_by_hierarchy, "Access by Hierarchy?" %>
    <%= check_box_tag :access_by_hierarchy %>
    Enabling Access by Hierarchy will make this doctrine accessible to all roles selected AND those above the listed role with the highest hierarchy ranking.
    <div class="form-group__access-hierarchy">
      Access Hierarchy Ranks
      <% @roles.each do |role| %>
        <div class="form-group__access-hierarchy__detail">
          <div class="form-group__access-hierarchy-detail__name">
            <%= role.name %>
          </div>
          <div class="form-group__access-hierarchy-detail__ranking">
            <%= role.hierarchy_ranking %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= submit_tag "Add new Doctrine" %>
  </div>
<% end %>

app/views/doctrines/show.html.erb
<div class="doctrine">

  <div class="doctrine__description">
    <div class="doctrine__name">
      <%= @doctrine.name %>
    </div>
    <div class="doctrine__description-text">
      At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
      <%= @doctrine.long_description %>
    </div>
  </div>
  <div class="doctrine__nav-links">
    <%= link_to "Fitting Index", doctrine_fittings_path(@doctrine) %>
    <% if current_user.director %>
      <%= link_to "Add New Fitting", new_doctrine_fitting_path(@doctrine) %>
    <% end %>
  </div>
  <div class="doctrine-progressions">
    <% @fittings_hash.each do |key, race| %>
      <div class="doctrine-progressions__race">
        <div class= "doctrine-progressions__race-title">
          <%= key %> Progressions
        </div>
        <% race.each do |key, progression | %>
          <div class="doctrine-progressions__progression">
            <div class="doctrine-progressions__progression-title">
              <%= key %> Progression
            </div>
            <% progression.each do |fit| %>
              <div class="doctrine-progressions__fit">
                <div class="doctrine-progressions__fit-name">
                  <%= fit.name %>
                </div>
                <div class="doctrine-progressions__fit-icon">
                  <% ship_type_id = fit.ship_dna.split(":")[0] %>
                  <img src="http://image.eveonline.com/render/<%= ship_type_id %>_256.png">
                </div>
                <div class="doctrine-progressions__fit-fleet-role">
                  Role: <%= fit.fleet_role %>
                </div>
                <div class="doctrine-progressions__fit-description">
                  <%= fit.description %>
                </div>
                <div class="doctrine-progressions__fit-link">
                  <%= link_to "#{fit.name} Details", doctrine_fitting_path(@doctrine, fit) %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/doctrines/update.html.erb
<h1>Doctrine#update</h1>
<p>Find me in app/views/doctrine/update.html.erb</p>