config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticated :user do
    root to: "doctrines#index", as: :authenticated_root
  end

  root to: redirect('/sign_in')

  resources :videos
  get 'latest/videos' => 'videos#latest'

  resources :operations

  resources :years do
    resources :months
  end

  resources :recruit_contacts
  get 'search/recruit_contacts' => 'recruit_contacts#search_name'

  resources :recruit_requirements
  resources :roles

  resources :members, only: [:index, :show]
  get 'members/add_new_api'
  get 'members/add_temporary_member'
  get 'refresh_member_list' => 'members#refresh_member_list'

  resources :fac_war_systems, only: [:index]
  get 'refresh_fac_war_systems' => 'fac_war_systems#refresh_fac_war_systems'

  resources :mission_groups do
    resources :missions do
      put 'obstructed' => 'missions#mark_obstructed'
      put 'complete' => 'missions#mark_complete'
      put 'incomplete' => 'missions#mark_incomplete'
    end

  end
  get 'accessible_agents' => 'missions#accessible_agents'

  resources :doctrines do
    resources :fittings
  end

  resources :fleet_commanders do
    resources :ratings
  end
end

app/models/mission.rb
# == Schema Information
#
# Table name: missions
#
#  id                :integer          not null, primary key
#  name              :string
#  user_id           :integer
#  fac_war_system_id :integer
#  loyalty_points    :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  mission_text      :text             default("{}"), is an Array
#  mission_group_id  :integer
#  incomplete        :boolean
#  complete          :boolean
#  obstructed        :boolean
#

class Mission < ActiveRecord::Base
  belongs_to :user
  belongs_to :mission_group

  validate :mission_text_cant_be_read_details

  def accessible_to_user?(user)
    # Check if the user is part of the mission group.
    self.mission_group.participant?(user)
  end

  def creatable_by_user?(user)
    # Allow the user to create a mission if they're a participant in the mission group
    self.mission_group.participant?(user)
  end

  def editable_by_user?(user)
    # Allow the user to edit a mission if they're the group or the mission's creator
    if self.mission_group.creator?(user) || self.creator?(user)
      return true
    else
      false
    end
  end

  # Check if the passed in user is the creator of the mission group
  def creator?(user)
    self.user_id == user.id
  end

  def status
    if self.incomplete
      return "Incomplete"
    elsif self.complete
      return "Complete"
    else
      return "Obstructed"
    end
  end

  private
    def mission_text_cant_be_read_details
      if mission_text[3].blank? || mission_text[7].blank?
        errors.add(:mission_text, "Mission Text cannot be from read details.")
      end
    end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def show
    @mission = Mission.find(params[:id])
    authorize @mission
  end

  def new
    @mission_group_id = params[:mission_group_id]
    @mission = Mission.new(mission_group_id: @mission_group_id)
    authorize @mission
  end

  def create
    # Cut the mission description into a tab delimited array
    mission_text = params["Mission Description"].split("\t")

    @mission = Mission.new(mission_text: mission_text, mission_group_id: params[:mission_group_id])
    authorize @mission
    if @mission.valid?
      params.permit(:mission_group_id)
      @mission.user_id = current_user.id
      @mission.name = @mission.mission_text[0].split("Objectives")[0].chomp(" ")
      @mission.loyalty_points = @mission.mission_text[7].split("Loyalty")[0].to_i

      # Populate the mission's state booleans
      @mission.incomplete = true
      @mission.complete = false
      @mission.obstructed = false

      # Extract the mission system name from the mission_text
      mission_system = @mission.mission_text[3].split(" ")[0]
      mission_system_name = mission_system.slice(4, mission_system.length)
      # Retrieve and store the solarSystemID
      @mission.fac_war_system_id = FacWarSystem.where(solarSystemName: mission_system_name).pluck(:solarSystemID)[0]

      # Save and redirect
      @mission.save
      redirect_to mission_group_missions_path(params[:mission_group_id])
    else
      flash[:alert] = "Missions cannot be indexed unless the text being submitted is from the offer or accepted stage. You submitted a copy of the read details stage."
      render 'new'
    end
  end

  def index
    @mission_group_id = params[:mission_group_id]
    @mission_group = MissionGroup.find(params[:mission_group_id])
    @missions = Mission.where(mission_group_id: params[:mission_group_id])

    # Authorize the user to view the index.
    if @missions.empty?
      authorize @mission_group.missions.new()
    else
      authorize @missions.first
    end

    @participants = Member.where(id: @mission_group.participants).pluck(:name)
    @total_potential_loyalty_points = @missions.where("incomplete = ?", true).sum(:loyalty_points)
    @total_earned_loyalty_points = @missions.where("complete = ?", true).sum(:loyalty_points)
    @total_obstructed_loyalty_points = @missions.where("obstructed = ?", true).sum(:loyalty_points)

    unique_user_count = @missions.pluck(:user_id).uniq.count
    if @total_potential_loyalty_points > 0
      @potential_loyalty_points_per_user = @total_potential_loyalty_points / unique_user_count
    else
      @potential_loyalty_points_per_user = 0
    end

    if @total_earned_loyalty_points > 0
      @earned_loyalty_points_per_user = @total_earned_loyalty_points / unique_user_count
    else
      @earned_loyalty_points_per_user = 0
    end

    if @total_obstructed_loyalty_points > 0
      @obstructed_loyalty_points_per_user = @total_obstructed_loyalty_points / unique_user_count
    else
      @obstructed_loyalty_points_per_user = 0
    end

    # Build a list of all the unique mission destinations for use in linking to dotlan
    @mission_system_list = ""
    uniq_mission_system_ids = @missions.where("incomplete = ? AND obstructed = ?", true, false).pluck(:fac_war_system_id).uniq
    system_names = FacWarSystem.where(solarSystemID: uniq_mission_system_ids).pluck(:solarSystemName)
    system_names.each do |system|
      @mission_system_list = @mission_system_list + "#{system},"
    end
    @mission_system_list.chomp!(",")

    # Build a list of all the unique obstructed mission destinations for use in linking to dotlan
    @obstructed_system_list = ""
    uniq_obstructed_system_ids = @missions.where("obstructed = ?", true).pluck(:fac_war_system_id).uniq
    system_names = FacWarSystem.where(solarSystemID: uniq_obstructed_system_ids).pluck(:solarSystemName)
    system_names.each do |system|
      @obstructed_system_list = @obstructed_system_list + "#{system},"
    end
    @obstructed_system_list.chomp!(",")

    # Build a hash of all unique systems & ids to display the system name from
    @system_names_hash = {}
    systems = FacWarSystem.where(solarSystemID: @missions.pluck(:fac_war_system_id).uniq).pluck(:solarSystemID, :solarSystemName)
    systems.each do |system|
      @system_names_hash.store(system[0], system[1])
    end
  end

  def mark_obstructed
    mission = Mission.find(params[:mission_id])
    authorize mission
    mission.obstructed = true
    mission.complete = false
    mission.incomplete = false
    mission.save
    redirect_to mission_group_missions_path(mission.mission_group_id)
  end

  def mark_complete
    mission = Mission.find(params[:mission_id])
    authorize mission
    mission.obstructed = false
    mission.complete = true
    mission.incomplete = false
    mission.save
    redirect_to mission_group_missions_path(mission.mission_group_id)
  end

  def mark_incomplete
    mission = Mission.find(params[:mission_id])
    authorize mission
    mission.obstructed = false
    mission.complete = false
    mission.incomplete = true
    mission.save
    redirect_to mission_group_missions_path(mission.mission_group_id)
  end

  def destroy
    @mission = Mission.find(params[:id])
    authorize @mission
    @mission.destroy
  end

  def accessible_agents
    @accessible_systems = []
    # Retrieve all state protectorate systems from the database
    systems = SolarSystem.where(missions: "State Protectorate")

    # Push all highsec state protectorate system names into the accessible_systems list
    @accessible_systems << systems.where("security > 0.45").pluck("solarSystemName")

    # Push all accessible lowsec state protectorate system names into the accessible_systems list
    @accessible_systems << FacWarSystem.where(solarSystemID: systems.pluck("solarSystemID")).where("\"occupyingFactionID\" = 500001 OR \"occupyingFactionID\" = 0 AND \"owningFactionID\" = 500001").pluck("solarSystemName")
    @accessible_systems.flatten!
    # Format the list for easy linking
    @accessible_system_list = ""
    @accessible_systems.each do |system|
      @accessible_system_list = @accessible_system_list + "#{system},"
    end
    @accessible_system_list.chomp!(",")
  end

  private
    #def create_mission_params
    #  params.permit("Mission Description")
    #end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/accessible_agents.html.erb
<div class="accessible-agents">
  <%= link_to "Accessible Agents", "http://evemaps.dotlan.net/map/Caldari_VS_Gallente/#{@accessible_system_list}" %>
</div>

app/views/missions/index.html.erb
<div class="mission__nav-links">
  <%= link_to "Accessible Agents", accessible_agents_path %>
  <%= link_to "Add New Mission to Group", new_mission_group_mission_path(@mission_group_id) %>
  <% if @mission_group.creator?(current_user) %>
    <%= link_to "Edit Participants", edit_mission_group_path(@mission_group_id) %>
    <%= link_to "Delete Group", mission_group_path(@mission_group_id), data: { confirm: "Are you sure?" }, method: :delete %>
  <% end %>
</div>
<div class="mission__group-name">
  <h1> <%= @mission_group.name %> </h1>
</div>
<div class="mission__lp-stats">
  <div class="mission__potential-lp">
    <div class="mission__potential-loyalty-points">
      <h2> Potential LP: <%= @total_potential_loyalty_points %> </h2>
    </div>
    <div class="mission__potential-loyalty-points-per-user">
      <h2> Potential LP/User: <%= @potential_loyalty_points_per_user %> </h2>
    </div>
  </div>

  <div class="mission__earned-lp">
    <div class="mission__earned-loyalty-points">
      <h2> Earned LP: <%= @total_earned_loyalty_points %> </h2>
    </div>
    <div class="mission__earned-loyalty-points-per-user">
      <h2> Earned LP/User: <%= @earned_loyalty_points_per_user %> </h2>
    </div>
  </div>

  <div class="mission__obstructed-lp">
    <div class="mission__obstructed-loyalty-points">
      <h2> Obstructed LP: <%= @total_obstructed_loyalty_points %> </h2>
    </div>
    <div class="mission__obstructed-loyalty-points-per-user">
      <h2> Obstructed LP/User: <%= @obstructed_loyalty_points_per_user %> </h2>
    </div>
  </div>
</div>

<div class="mission__listing" >
  <div class="mission__mission-map">
    <%= link_to "Mission Map", "http://evemaps.dotlan.net/map/Caldari_VS_Gallente/#{@mission_system_list}" %>
  </div>
  <div class="mission__obstructed-mission-map">
    <% if !@obstructed_system_list.blank? %>
      <%= link_to "Obstructed Systems", "http://evemaps.dotlan.net/map/Caldari_VS_Gallente/#{@obstructed_system_list}" %>
    <% end %>
  </div>
  <div class="mission__participants">
    Participants:
    <% @participants.each do |participant| %>
      <div class="mission__participant-name">
        <%= participant %>
      </div>
    <% end %>
  </div>
  <table class="mission__mission-table">
    <thead>
      <tr>
        <th> Name </th>
        <th> Posted By </th>
        <th> Destination </th>
        <th> Loyalty Points </th>
        <th> Status </th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.name %> </td>
        <td> <%= mission.user.main_character_name %> </td>
        <td><button type"button" onclick="CCPEVE.setDestination(<%= mission.fac_war_system_id %>)"> <%= @system_names_hash[mission.fac_war_system_id] %></button></td>
        <td> <%= mission.loyalty_points %> </td>
        <td> <%= mission.status %> </td>
        <% if mission.creator?(current_user) || mission.mission_group.creator?(current_user) %>
          <% if mission.incomplete %>
            <td> <%= link_to "Mark Complete", mission_group_mission_complete_path(@mission_group_id, mission), method: :put %> </td>
            <td> <%= link_to "Mark Obstructed", mission_group_mission_obstructed_path(@mission_group_id, mission), method: :put %> </td>
          <% end %>
          <% if mission.complete %>
            <td> <%= link_to "Mark Incomplete", mission_group_mission_incomplete_path(@mission_group_id, mission), method: :put %> </td>
            <td> <%= link_to "Mark Obstructed", mission_group_mission_obstructed_path(@mission_group_id, mission), method: :put %> </td>
          <% end %>
          <% if mission.obstructed %>
            <td> <%= link_to "Mark Complete", mission_group_mission_complete_path(@mission_group_id, mission), method: :put %> </td>
            <td> <%= link_to "Mark Incomplete", mission_group_mission_incomplete_path(@mission_group_id, mission), method: :put %> </td>
          <% end %>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/missions/new.html.erb
<%= form_tag mission_group_missions_path(params[:mission_group_id]) do %>
  <%= render "shared/error_messages", :target => @mission %>
  <%= text_area_tag 'Mission Description', nil, size: "50x25" %>
  <%= submit_tag "Add Mission" %>
<% end %>

app/views/missions/show.html.erb
<%= @mission.name %>
<%= @mission.user.main_character_name %>
<%= @mission.fac_war_system_id %>
<%= @mission.loyalty_points %>